apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.anypointSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ANYPOINT_CLIENT_ID: {{ .Values.anypointSecret.clientId | quote }}
  ANYPOINT_CLIENT_SECRET: {{ .Values.anypointSecret.clientSecret | quote }}
